### ISSUE TITLE
metadata (column) description

### ISSUE THREAD

**Issue by kasperdanielhansen** [LieberInstitute/recount3#2]
We need a URL with documentation on all the many metadata fields. Some are just grabbed from SRA, some are obvious, and some are not. Tagging @ChristopherWilks

**Comment by ChristopherWilks** [comment]
So for GTExV2 there's:
http://snaptron.cs.jhu.edu/data/gtexv2/samples.field_descriptions.tsv
and
http://snaptron.cs.jhu.edu/data/gtexv2/samples.subject_field_descriptions.tsv

from the GTEx portal.

I'm thinking @kasperdanielhansen your primarily referring to the QC fields?

**Comment by lcolladotor** [comment]
We now have the QC fields documented at http://rna.recount.bio/docs/quality-check-fields.html.
