### ISSUE TITLE
TCGA data: how do you generate the metadata?

### ISSUE THREAD

**Issue by bandrewfox** [LieberInstitute/recount3#24]
I really like using your version of the TCGA metadata since it has so many fields and it comes with the uniformly aligned/processed expression data. But, I'm curious if you can point me to a github repo or some other documentation which describes how the TCGA metadata was curated. I'm interested in knowing where you downloaded the data from, the version/date that you grabbed it, and how you mapped it to your final metadata which I see in colData(rse_obj).

Thanks so much!

**Comment by lcolladotor** [comment]
Hi,

I believe that it comes from the metadata we compiled for TCGA as part of the `recount2` project. That would be the scripts from https://github.com/leekgroup/recount-website/tree/master/metadata/tcga_prep.

Best,
Leo
