### ISSUE TITLE
deseq 2 with RSE

### ISSUE THREAD

**Issue by lfperales** [LieberInstitute/recount3#25]
Hello, 

I run DESeq using one of the studies. However I'm getting this plot. I think whenever I download the data I get different results, because before I got a nice volcano plot and now I'm getting this one. Can you please help me? 

![image](https://user-images.githubusercontent.com/112426849/188657396-4a84a61a-9607-40ef-a49c-5a0466f529a4.png)
 
I normalized the counts following this code:

assay(rse_gene,"counts") <- compute_read_counts(
  rse_gene,
  round = TRUE,
  avg_mapped_read_length = "recount_qc.star.average_mapped_length"
)

assayNames(rse_gene)

**Comment by lcolladotor** [comment]
Hi!

Thanks for your interest in our software. 

Thanks for the PR / issue. A close family of mine was diagnosed with cancer, so my availability is limited right now.

It might take me a few weeks to reply properly. 

Best,
Leo

**Comment by lcolladotor** [comment]
Hi @lfperales,

I'll need more code and/or background to understand your question. Can you try using `reprex` https://reprex.tidyverse.org/. https://youtu.be/8bBo3B7N8YQ might be useful.

Thanks,
Leo
