### ISSUE TITLE
[BUG] 'recount3_url' is not a valid supported URL

### ISSUE THREAD

**Issue by uuihbgg1** [LieberInstitute/recount3#32]
> available_projects()
Error: 'recount3_url' is not a valid supported URL since it's missing the URL/<organism>/homes_index text file or 'recount3_url' is not an existing directory in your file system.

Then, I try to set the value of the "organism" and "recount3_url" arguments. 
> mouse_projects <- available_projects(organism = "mouse")
Error: 'recount3_url' is not a valid supported URL since it's missing the URL/<organism>/homes_index text file or 'recount3_url' is not an existing directory in your file system.

> mouse_projects <- available_projects(organism = "mouse",
                                       recount3_url = "http://snaptron.cs.jhu.edu/data/temp/recount3test")
Error: 'recount3_url' is not a valid supported URL since it's missing the URL/<organism>/homes_index text file or 'recount3_url' is not an existing directory in your file system.

The version of "recount3" is 1.91, and the version of R is 4.2.2

Is this an issue with the provider service? Or am I missing something?
Thank you

**Comment by lcolladotor** [comment]
Hi,

Are you using Windows? If so, try using `options(recount3_url = "https://recount-opendata.s3.amazonaws.com/recount3/release")`.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi again,

If you are a Windows user, this issue has now been addressed by the internal switch from `RCurl::url.exists()` to `httr::http_error()`. You can gain access to these updates by installing `recount3` version 1.10.2 (bioc-release aka 3.17) or 1.11.2 (bioc-devel aka 3.18).

Best,
Leo
