### ISSUE TITLE
Identify the label in the datasets

### ISSUE THREAD

**Issue by kolskydor** [LieberInstitute/recount3#33]
Hey, how can i identify in each data set if they are labeld/not and if they do what is the column which contain the label?

Thanks!

**Comment by lcolladotor** [comment]
Hi,

I don't understand your question. It's possible the information at http://rna.recount.bio/docs/quality-check-fields.html will be useful to you. Also see http://research.libd.org/recount3/reference/expand_sra_attributes.html for the datasets from SRA.

Best,
Leo

**Comment by lcolladotor** [comment]
I'm closing this issue as we haven't heard any new details that would help us answer the question better. If you do have more details, feel free to re-open the issue.

Best,
Leo
