### ISSUE TITLE
Error in match.arg(project_home) 

### ISSUE THREAD

**Issue by kayserb** [LieberInstitute/recount3#38]
Thank you for the great package! I recently tried to download a study using the provided code (below) and got the following error (further below). 

**Code**
se = recount3::create_rse_manual(
  project = "SRP094781",
  project_home = "data_sources/sra",
  organism = "human",
  annotation = "gencode_v26",
  type = "gene"
)

**Error message**
Error in match.arg(project_home) : 
  'arg' should be one of “<!DOCTYPE html>”, “<html lang="en">”, “<head>”, “	”, “	”, “	<script>”, “	  window.dataLayer = window.dataLayer || [];”, “	  function gtag(){dataLayer.push(arguments);}”, “	  gtag('js', new Date());”, “	  gtag('config', 'G-BKJ282JSQ6');”, “	</script>”, “	<meta name="viewport" content="width=device-width">”, “	<meta charset="utf-8">”, “	<meta http-equiv="x-ua-compatible" content="ie=edge">”, “	<title>Domain unavailable</title>”, “	<meta name="description" content="This page is unavailable.">”, “	<style>”, “		body,html{height:100%;margin:0;font-family:Arial}.a0 svg,.a0 svg path{width:100px}h1{margin-bottom:40px;margin-top:0}p{color:rgba(0,0,0,.6)}a,a:active,a:hover,a:link,a:visited{text-decoration:none;color:#116EB7}.a1{margin-top:40px}.a10 .bb{display:flex;justify-
In addition: Warning message:
In readLines(homes_url) :
  incomplete final line found on 'http://duffel.rail.bio/recount3/human/homes_index'

**sessionInfo()**
R version 4.3.1 (2023-06-16)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: US/Pacific
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0            dplyr_1.1.3                 blob_1.2.4                  filelock_1.0.2             
 [5] R.utils_2.12.2              Biostrings_2.68.1           bitops_1.0-7                fastmap_1.1.1              
 [9] RCurl_1.98-1.12             BiocFileCache_2.8.0         GenomicAlignments_1.36.0    XML_3.99-0.14              
[13] digest_0.6.33               estimability_1.4.1          lifecycle_1.0.3             RSQLite_2.3.2              
[17] magrittr_2.0.3              compiler_4.3.1              rlang_1.1.1                 tools_4.3.1                
[21] utf8_1.2.3                  yaml_2.3.7                  data.table_1.14.8           rtracklayer_1.60.1         
[25] knitr_1.44                  S4Arrays_1.0.6              bit_4.0.5                   curl_5.1.0                 
[29] DelayedArray_0.26.7         abind_1.4-5                 BiocParallel_1.34.2         purrr_1.0.2                
[33] BiocGenerics_0.46.0         R.oo_1.25.0                 grid_4.3.1                  stats4_4.3.1               
[37] fansi_1.0.5                 xtable_1.8-4                emmeans_1.8.8               SummarizedExperiment_1.30.2
[41] cli_3.6.1                   mvtnorm_1.2-3               rmarkdown_2.25              crayon_1.5.2               
[45] generics_0.1.3              rstudioapi_0.15.0           httr_1.4.7                  tzdb_0.4.0                 
[49] rjson_0.2.21                sessioninfo_1.2.2           DBI_1.1.3                   qusage_2.34.0              
[53] cachem_1.0.8                zlibbioc_1.46.0             fftw_1.0-7                  parallel_4.3.1             
[57] BiocManager_1.30.22         XVector_0.40.0              restfulr_0.0.15             matrixStats_1.0.0          
[61] vctrs_0.6.3                 Matrix_1.6-1.1              IRanges_2.34.1              hms_1.1.3                  
[65] S4Vectors_0.38.2            bit64_4.0.5                 limma_3.56.2                tidyr_1.3.0                
[69] recount3_1.10.2             glue_1.6.2                  codetools_0.2-19            GenomeInfoDb_1.36.4        
[73] GenomicRanges_1.52.1        BiocIO_1.10.0               tibble_3.2.1                pillar_1.9.0               
[77] htmltools_0.5.6.1           GenomeInfoDbData_1.2.10     R6_2.5.1                    dbplyr_2.3.4               
[81] evaluate_0.22               lattice_0.21-9              Biobase_2.60.0              readr_2.1.4                
[85] R.methodsS3_1.8.2           Rsamtools_2.16.0            memoise_2.0.1               nlme_3.1-163               
[89] xfun_0.40                   MatrixGenerics_1.12.3       pkgconfig_2.0.3

**Comment by lcolladotor** [comment]
Hi!

Thank you for your interest in `recount3`. I tried reproducing your error and wasn't able to. This was using the same version of `recount3`: 1.10.2. My macOS operating system version is newer than yours though. Maybe this is related to https://github.com/Bioconductor/BiocFileCache/issues/48.

Best,
Leo

``` r
se <- recount3::create_rse_manual(
    project = "SRP094781",
    project_home = "data_sources/sra",
    organism = "human",
    annotation = "gencode_v26",
    type = "gene"
)
#> 2023-11-30 17:18:20.68776 downloading and reading the metadata.
#> 2023-11-30 17:18:21.246725 caching file sra.sra.SRP094781.MD.gz.
#> 2023-11-30 17:18:21.801745 caching file sra.recount_project.SRP094781.MD.gz.
#> 2023-11-30 17:18:22.411877 caching file sra.recount_qc.SRP094781.MD.gz.
#> 2023-11-30 17:18:23.03163 caching file sra.recount_seq_qc.SRP094781.MD.gz.
#> 2023-11-30 17:18:23.570396 caching file sra.recount_pred.SRP094781.MD.gz.
#> 2023-11-30 17:18:23.645317 downloading and reading the feature information.
#> 2023-11-30 17:18:24.193049 caching file human.gene_sums.G026.gtf.gz.
#> 2023-11-30 17:18:24.804772 downloading and reading the counts: 109 samples across 63856 features.
#> 2023-11-30 17:18:25.321777 caching file sra.gene_sums.SRP094781.G026.gz.
#> 2023-11-30 17:18:26.115137 constructing the RangedSummarizedExperiment (rse) object.
se
#> class: RangedSummarizedExperiment 
#> dim: 63856 109 
#> metadata(8): time_created recount3_version ... annotation recount3_url
#> assays(1): raw_counts
#> rownames(63856): ENSG00000278704.1 ENSG00000277400.1 ...
#>   ENSG00000182484.15_PAR_Y ENSG00000227159.8_PAR_Y
#> rowData names(10): source type ... havana_gene tag
#> colnames(109): SRR5088832 SRR5088891 ... SRR5088893 SRR5088917
#> colData names(175): rail_id external_id ...
#>   recount_pred.curated.cell_line BigWigURL
options(width = 120)
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16)
#>  os       macOS Sonoma 14.0
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Mexico_City
#>  date     2023-11-30
#>  pandoc   3.1.5 @ /opt/homebrew/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
#>  package              * version   date (UTC) lib source
#>  abind                  1.4-5     2016-07-21 [1] CRAN (R 4.3.0)
#>  Biobase                2.60.0    2023-04-25 [1] Bioconductor
#>  BiocFileCache          2.8.0     2023-04-25 [1] Bioconductor
#>  BiocGenerics           0.46.0    2023-04-25 [1] Bioconductor
#>  BiocIO                 1.10.0    2023-04-25 [1] Bioconductor
#>  BiocParallel           1.34.2    2023-05-28 [1] Bioconductor
#>  Biostrings             2.68.1    2023-05-16 [1] Bioconductor
#>  bit                    4.0.5     2022-11-15 [1] CRAN (R 4.3.0)
#>  bit64                  4.0.5     2020-08-30 [1] CRAN (R 4.3.0)
#>  bitops                 1.0-7     2021-04-24 [1] CRAN (R 4.3.0)
#>  blob                   1.2.4     2023-03-17 [1] CRAN (R 4.3.0)
#>  cachem                 1.0.8     2023-05-01 [1] CRAN (R 4.3.0)
#>  cli                    3.6.1     2023-03-23 [1] CRAN (R 4.3.0)
#>  codetools              0.2-19    2023-02-01 [1] CRAN (R 4.3.1)
#>  crayon                 1.5.2     2022-09-29 [1] CRAN (R 4.3.0)
#>  curl                   5.0.2     2023-08-14 [1] CRAN (R 4.3.1)
#>  data.table             1.14.8    2023-02-17 [1] CRAN (R 4.3.0)
#>  DBI                    1.1.3     2022-06-18 [1] CRAN (R 4.3.0)
#>  dbplyr                 2.3.3     2023-07-07 [1] CRAN (R 4.3.0)
#>  DelayedArray           0.26.7    2023-07-30 [1] Bioconductor
#>  digest                 0.6.33    2023-07-07 [1] CRAN (R 4.3.0)
#>  dplyr                  1.1.3     2023-09-03 [1] CRAN (R 4.3.0)
#>  evaluate               0.21      2023-05-05 [1] CRAN (R 4.3.0)
#>  fansi                  1.0.4     2023-01-22 [1] CRAN (R 4.3.0)
#>  fastmap                1.1.1     2023-02-24 [1] CRAN (R 4.3.0)
#>  filelock               1.0.2     2018-10-05 [1] CRAN (R 4.3.0)
#>  fs                     1.6.3     2023-07-20 [1] CRAN (R 4.3.0)
#>  generics               0.1.3     2022-07-05 [1] CRAN (R 4.3.0)
#>  GenomeInfoDb           1.36.3    2023-09-10 [1] Bioconductor
#>  GenomeInfoDbData       1.2.10    2023-05-06 [1] Bioconductor
#>  GenomicAlignments      1.36.0    2023-04-25 [1] Bioconductor
#>  GenomicRanges          1.52.0    2023-04-25 [1] Bioconductor
#>  glue                   1.6.2     2022-02-24 [1] CRAN (R 4.3.0)
#>  htmltools              0.5.6     2023-08-10 [1] CRAN (R 4.3.0)
#>  httr                   1.4.7     2023-08-15 [1] CRAN (R 4.3.0)
#>  IRanges                2.34.1    2023-07-02 [1] Bioconductor
#>  knitr                  1.44      2023-09-11 [1] CRAN (R 4.3.0)
#>  lattice                0.21-8    2023-04-05 [1] CRAN (R 4.3.1)
#>  lifecycle              1.0.3     2022-10-07 [1] CRAN (R 4.3.0)
#>  magrittr               2.0.3     2022-03-30 [1] CRAN (R 4.3.0)
#>  Matrix                 1.6-1     2023-08-14 [1] CRAN (R 4.3.0)
#>  MatrixGenerics         1.12.3    2023-07-30 [1] Bioconductor
#>  matrixStats            1.0.0     2023-06-02 [1] CRAN (R 4.3.0)
#>  memoise                2.0.1     2021-11-26 [1] CRAN (R 4.3.0)
#>  pillar                 1.9.0     2023-03-22 [1] CRAN (R 4.3.0)
#>  pkgconfig              2.0.3     2019-09-22 [1] CRAN (R 4.3.0)
#>  purrr                  1.0.2     2023-08-10 [1] CRAN (R 4.3.0)
#>  R.cache                0.16.0    2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3            1.8.2     2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo                   1.25.0    2022-06-12 [1] CRAN (R 4.3.0)
#>  R.utils                2.12.2    2022-11-11 [1] CRAN (R 4.3.0)
#>  R6                     2.5.1     2021-08-19 [1] CRAN (R 4.3.0)
#>  RCurl                  1.98-1.12 2023-03-27 [1] CRAN (R 4.3.0)
#>  recount3               1.10.2    2023-05-08 [1] Bioconductor
#>  reprex                 2.0.2     2022-08-17 [1] CRAN (R 4.3.0)
#>  restfulr               0.0.15    2022-06-16 [1] CRAN (R 4.3.0)
#>  rjson                  0.2.21    2022-01-09 [1] CRAN (R 4.3.0)
#>  rlang                  1.1.1     2023-04-28 [1] CRAN (R 4.3.0)
#>  rmarkdown              2.24      2023-08-14 [1] CRAN (R 4.3.1)
#>  Rsamtools              2.16.0    2023-04-25 [1] Bioconductor
#>  RSQLite                2.3.1     2023-04-03 [1] CRAN (R 4.3.0)
#>  rstudioapi             0.15.0    2023-07-07 [1] CRAN (R 4.3.0)
#>  rtracklayer            1.60.1    2023-08-20 [1] Bioconductor
#>  S4Arrays               1.0.6     2023-09-10 [1] Bioconductor
#>  S4Vectors              0.38.1    2023-05-02 [1] Bioconductor
#>  sessioninfo            1.2.2     2021-12-06 [1] CRAN (R 4.3.0)
#>  styler                 1.10.2    2023-08-29 [1] CRAN (R 4.3.0)
#>  SummarizedExperiment   1.30.2    2023-06-11 [1] Bioconductor
#>  tibble                 3.2.1     2023-03-20 [1] CRAN (R 4.3.0)
#>  tidyselect             1.2.0     2022-10-10 [1] CRAN (R 4.3.0)
#>  utf8                   1.2.3     2023-01-31 [1] CRAN (R 4.3.0)
#>  vctrs                  0.6.3     2023-06-14 [1] CRAN (R 4.3.0)
#>  withr                  2.5.0     2022-03-03 [1] CRAN (R 4.3.0)
#>  xfun                   0.40      2023-08-09 [1] CRAN (R 4.3.0)
#>  XML                    3.99-0.14 2023-03-19 [1] CRAN (R 4.3.0)
#>  XVector                0.40.0    2023-04-25 [1] Bioconductor
#>  yaml                   2.3.7     2023-01-23 [1] CRAN (R 4.3.0)
#>  zlibbioc               1.46.0    2023-04-25 [1] Bioconductor
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

<sup>Created on 2023-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kayserb** [comment]
Thanks for looking into this for me, @lcolladotor. I ran it again and still have the problem. I'll update my OS soon, and will try again after that.

Best,

Brandon
