### ISSUE TITLE
Unable to access or download data

### ISSUE THREAD

**Issue by MB571** [LieberInstitute/recount3#52]
Previously the command

`human_projects <- available_projects(recount3_url = "http://duffel.rail.bio/recount3",organism = "human")
`
was working however now im getting the errors

`Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Run `rlang::last_trace()` to see where the error occurred.`

has anyone encountered this before? Also ive noticed the url "http://duffel.rail.bio/recount3" is returning blank?

**Comment by lcolladotor** [comment]
Hi,

Thanks for your interest in using `recount3`. The error you encountered was discovered in BioC version 3.17 (which was a `devel` version) and was fixed for the 3.18 release (the current `release` version).

You can check which Bioconductor version you have installed with:

```R
BiocManager::version()
```

Then check that you have a valid installation with:

```R
BiocManager::valid()
```

Best,
Leo
